import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackButton from "@/components/BackButton";
import { DataProvider } from "../context/DataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App mediciones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="text-4xl text-white bg-cyan-900 m-1 p-3 text-center rounded relative">
            <BackButton></BackButton>
            <h1 className="text-center"> Mediciones Eléctricas IEC 62353 </h1>
          </div>
          <DataProvider>{children}</DataProvider>
        </body>
      </>
    </html>
  );
}
