import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Mediciones</title>
      <>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <h1 className="text-4xl text-white bg-cyan-900 m-1 p-3 text-center rounded">
            {" "}
            Mediciones Eléctricas IEC 62353{" "}
          </h1>
          {children}
        </body>
      </>
    </html>
  );
}
